### ISSUE TITLE
Unable to find gulp-cli

### ISSUE THREAD

**Issue by mikeerickson** [mbolaric/vscode-tasks-panel#4]
Receive the following error when Tasks are loaded.  FWIW, the `gulp-cli` is installed globally as it should be

```
Error: Cannot find module 'gulp-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/mikee/Documents/code/js/gulp-4/node_modules/.bin/gulp:3:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```
![image](https://user-images.githubusercontent.com/183153/54377085-ae252800-4641-11e9-885b-4fb128b03252.png)

**Comment by mbolaric** [comment]
I cannot reproduce this behavior on my computer (Ubuntu 18.04.1, VSCode 1.32.3).
I have same configuration, `gulp-cli` installed globally and gulp 4 installed with `npm` locally. 

I need more information or sample project that have this problem.

![image](https://user-images.githubusercontent.com/36398597/54496019-97edc500-48ea-11e9-9dfa-50e4119e4da2.png)

**Comment by mikeerickson** [comment]
Yes, that is what appears when I call `gulp —version`. I will try and see if I can find conflict
